# Compiler
CXX := g++-15

# Program name (executable)
PROG := producerconsumer

# Directories
BIN_DIR   := bin
BUILD_DIR := build
SRC_DIR   := src
INC_DIR   := include
DOC_DIR   := doc

# Compiler flags
CXXFLAGS := -Wall -Wextra -pedantic -std=c++20 -I$(INC_DIR)

# Source and object files
# main.cpp is in the repository root
# Other .cpp files are inside src/
SOURCES := main.cpp $(wildcard $(SRC_DIR)/*.cpp)
OBJECTS := $(BUILD_DIR)/main.o \
           $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/%.o,$(wildcard $(SRC_DIR)/*.cpp))

# Dependency files generated by the compiler
DEPS := $(OBJECTS:.o=.d)

# Default target
.PHONY: all
all: $(BIN_DIR)/$(PROG)

# Directory targets
# Create directories only when they do not exist
$(BIN_DIR):
	mkdir -p $@

$(BUILD_DIR):
	mkdir -p $@

# Linking
$(BIN_DIR)/$(PROG): $(OBJECTS) | $(BIN_DIR)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)
	@echo "> Executable '$@' created"

# Compilation
$(BUILD_DIR)/main.o: main.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -MMD -MP -c $< -o $@
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -MMD -MP -c $< -o $@

# Include automatically generated header dependencies.
-include $(DEPS)

# Debug build
.PHONY: debug
debug: CXXFLAGS += -g -O0
debug: clean
debug: $(BIN_DIR)/$(PROG)

# Documentation with Doxygen
.PHONY: doxy doc
doxy:
	doxygen -g
doc:
	doxygen

# Clean
.PHONY: clean
clean:
	rm -rf $(BIN_DIR) $(BUILD_DIR)
